platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

install! 'cocoapods',
         :preserve_pod_file_structure => true
#         :generate_multiple_pod_projects => true

target 'RaServicesExample' do
  
  pod 'RaServices', path: '../'
  pod 'RaServicesCore', path: '../'
  pod 'RaServicesBehavior', path: '../'
  pod 'RaServicesURLNavigate', path: '../'

  pod 'Order', path: './Services/Order'
  pod 'OrderInterface', path: './Services/OrderInterface'

end
