platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

install! 'cocoapods',
         :preserve_pod_file_structure => true
#         :generate_multiple_pod_projects => true

target 'RaModularExample' do
  
  pod 'RaModular', path: '../'
  pod 'RaModularCore', path: '../'
  pod 'RaModularRouter', path: '../'
  pod 'RaModularBehavior', path: '../'

  pod 'Order', path: './Services/Order'
  pod 'OrderInterface', path: './Services/OrderInterface'

end
